### ISSUE TITLE
repKlines can fail and end up in an infinite loop

### ISSUE THREAD

**Issue by lilltroll77** [hughestu/MATLAB-Binance-API#1]
For a large request of data, the repKlines can fail in the while loop when n = height(Ttemp) returns a value smaller than 1000

**Comment by hughestu** [comment]
Another good point, do you have an example of the code that caused this?

**Comment by hughestu** [comment]
i.e. what were your inputs to pub.repKlines?

**Comment by lilltroll77** [comment]
Sorry for the delay

I think that if you run '1m' since 2021-01-01, it will fail when it hits the first part of missing data.

Try 
dt=datetime('13-Aug-2021 03:59:00'); r=  pub.repKlines('QTUMUSDT','1m', [dt+minutes(1) dt+minutes(60)])

as an example

**Comment by hughestu** [comment]
Thanks, Mikael. 

I assumed previously that requesting 1000 rows of data would return 1000 rows of data, but that is not the case. There are often gaps in trading and hence data for a symbol. I've pushed changes to the repository to fix this. You can download from GitHub and verify with the following code: 
```
t=datetime('13-Aug-2021 03:59:00');
r= pub.repKlines('QTUMUSDT','1m', [t-hours(60) t+hours(60)]);
figure(), plot(r.Time,r.open,'.')
ylabel('USDT'),title('QTUM/USDT'), set(gca,'fontSize',14)
```
