### ISSUE TITLE
Error in spot.accountInfo

### ISSUE THREAD

**Issue by jzsfvss** [hughestu/MATLAB-Binance-API#11]
Hi Turlough. I was delighted to chance upon your package. I greatly appreciate your invested time and effort, and encourage you to keep up the good work! I am going through your given steps to get started, and I'm stuck on step 3:

`[~,~,response] = spot.accountInfo`

I'm getting the following error in MATLAB R2021a Update 5:

_Unrecognized function or variable 'isValidrecv'._

_Error in spot.accountInfo (line 16)_
    _OPT.recvWindow (1,1) {isValidrecv(OPT.recvWindow)} = 5000_

Thanks!

**Comment by hughestu** [comment]
Thank you. Was the subfunctions folder on the MATLAB path when you tried to do this?

**Comment by jzsfvss** [comment]
It wasn't, but I now added it and the other subfolders. Getting a different error now:

_Error using isValidrecv (line 3)_
_Invalid default value for argument 'recvWindow'. Too many output arguments._

_Error in spot.accountInfo (line 16)_
    _OPT.recvWindow (1,1) {isValidrecv(OPT.recvWindow)} = 5000_

**Comment by hughestu** [comment]
Can you confirm that the [isValidrecv](https://github.com/hughestu/MATLAB-Binance-API/blob/main/subfunctions/isValidrecv.m) function is identical to the one in my repository?

**Comment by jzsfvss** [comment]
Sorry for my belated reply. You were right. I removed the "end" from the end of isValidrecv. Working fine now. I never put that in functions, not sure what its use is. Perhaps because no output is defined.
