### ISSUE TITLE
Error imargin NewOrder

### ISSUE THREAD

**Issue by stevelka** [hughestu/MATLAB-Binance-API#12]
Hi,

I can't create an order of imargin type:

Error using newMarginOrderObject.LIMIT
Too many input arguments.

Error in imargin.newOrder (line 64)
obj = newMarginOrderObject.LIMIT(true) ;

thanks

**Comment by hughestu** [comment]
Yes, this is a consequence of reorganising some of the code in a previous update. Following this [commit](https://github.com/hughestu/MATLAB-Binance-API/commit/8fc48e1068b9d40b191015d55d4fa13b7f569798), the imargin orders should all be working properly again.
