### ISSUE TITLE
error using sendRequest

### ISSUE THREAD

**Issue by bendlflo** [hughestu/MATLAB-Binance-API#13]
Hi there,
I've been looking for such a tool for quite some time! I'll definitely reward you if it turns out well for me. :) To get started though I run into trouble. Copied in testnet API keys. Then running a test file in the same folder:

clear; clc
addpath(genpath(pwd));
[~,~,response] = spot.accountInfo

Gives error:
Error using sendRequest (line 85)
Client Error: Unauthorized
Server Error Code: -2015
Server Message: Invalid API-key, IP, or permissions for action.

Error in spot.accountInfo (line 21)
response = sendRequest(OPT,endPoint,'GET');

Error in Test (line 10)
[~,~,response] = spot.accountInfo

Any other settings I need to take care of?

Thanks a lot in advance,
Florian

**Comment by bendlflo** [comment]
Just figured that baseURL needs to be set to: https://testnet.binance.vision

**Comment by hughestu** [comment]
Hi Florian,

I hadn't actually set up TestNet originally but, as you say, it seems that changing the getBaseURL() function will do the trick. Have fun.

All the best,
Turlough.

**Comment by hughestu** [comment]
By the way, thank you. I hope it works out well for you! All the same, don't risk anything you're not willing to lose 😅

**Comment by bendlflo** [comment]
Thanks for your concerns :) Hope its already working for you! Looking forward to see if I get this to work how I want to.
