### ISSUE TITLE
imargin cancel All Orders

### ISSUE THREAD

**Issue by stevelka** [hughestu/MATLAB-Binance-API#15]
Hi, I think there is an issue with this function :

>> imargin.cancelAllOrders('ETHBUSD')
Error using sendRequest (line 81)
Client Error: Bad Request
Server Error Code: -2011
Server Message: Unknown order sent.

Error in iimargin.cancelAllOrders (line 26)
response = sendRequest(OPT,endPoint,'DELETE');

may be the function is not looking for orders in the imargin account!

have a nice day!

**Comment by hughestu** [comment]
This was fixed in v0.1.4. You should be able to do this just fine in the most recent version. If you are still experiencing this problem I will reopen.

**Comment by stevelka** [comment]
thanks bro.

**Comment by hughestu** [comment]
No problem.
