### ISSUE TITLE
kline fails when response is empty

### ISSUE THREAD

**Issue by lilltroll77** [hughestu/MATLAB-Binance-API#2]
Something like this is needed:

response = sendRequest(OPT,'/api/v3/klines','GET');

w = getWeights(response);
if(isempty(response.Body.Data))
    varargout{1}=[];
else
...

**Comment by hughestu** [comment]
Thanks, this is a really good point. I actually meant to do a pass on the code for ensuring all functions handle the case of empty api responses. Some functions do it, others don't - somewhere down the line I forgot to do it for all of them. I'm glad you brought it to my attention though and I will address this asap.

**Comment by hughestu** [comment]
I've pushed changes now to address this along with output handling for a few other functions. Cheers!
