### ISSUE TITLE
repKlines fails if timeRange has a TimeZone

### ISSUE THREAD

**Issue by lilltroll77** [hughestu/MATLAB-Binance-API#3]
Line 49:
timeRange<=datetime() 

fails if the input timeRange has a timeZone.

Nice if the call would work with any timeZone for timeRange

**Comment by lilltroll77** [comment]
Keep up the good work! 
We are a group that is developing bots based on your code, but at the moment just paper money, until we can prove code stability and profit.

**Comment by hughestu** [comment]
Cool. Nice to know.

> Nice if the call would work with any timeZone for timeRange

The calls now work with any timezone, and any valid timeRange within Binance's trading history for klines, repKlines, aggTrades and repAggTrades. Every other function using datetimes **should** incorporate datetime2posix, which assigns the local timezone if none has been specified. In the case you want to use a different timezone (e.g. gmt) then modify subfunctions/datetime2posix accordingly.

**Comment by lilltroll77** [comment]
I think you broke the 'limit' now

>> TT = pub.klines( 'BTCUSDT' , '1w' , 'limit',500);
Unrecognized function or variable 'tZone'.

**Comment by hughestu** [comment]
Sorry, I went off the radar there. I think this was a relatively simple follow up. If there is nothing else I will close this issue and similarly if you notice any other issues do let me know. I appreciate your input.
