### ISSUE TITLE
Undefined function or variable 'QueryParameter'.

### ISSUE THREAD

**Issue by stevelka** [hughestu/MATLAB-Binance-API#4]
Hi, I use Matlab R2016b. I guet the following error trying to connect :

'Undefined function or variable 'QueryParameter'.

Can you help please ?

thanks!

**Comment by hughestu** [comment]
Hi, can tell me which function gave you this issue?

**Comment by stevelka** [comment]
Hi, its  spot.accountInfo; 
I wrote :

          import matlab.net.*

          OPT.recvWindow (1,1) = 5000     ;   
          OPT.username (1,:) = 'default';
         spot.accountInfo(OPT);

The error happend in : 

"Error in sendRequest 
QP =   QueryParameter(s); "       


I tryed also to change the command in sendRequest like this

QP = matlab.net.QueryParameter(s)

I got the error
"Undefined variable "matlab" or class "matlab.net.QueryParameter".


buy the way I have Matlab R2016a.


thanks a lot for your feedback

**Comment by stevelka** [comment]
I thought may be I dont have the package matlab.net installed, but the commande 
import matlab.net.*   did not give un error!

**Comment by stevelka** [comment]
I downloaded the last version of Matlab (infortunatly its a a trial version), but your code works fine.

Excellent job you did.  Thanks

**Comment by hughestu** [comment]
You appear to have resolved this one yourself. This was a compatibility issue; the [HTTP package](https://uk.mathworks.com/help/releases/R2016b/matlab/call-wsdl-web-services_bu9hx2b-1.html) that I used in my code requires R2016b or later.

**Comment by hughestu** [comment]
> 
> 
> I thought may be I dont have the package matlab.net installed, but the commande import matlab.net.* did not give un error!

`import someNonExistingPackageName.*` does not actually throw an error, perhaps it should.
