### ISSUE TITLE
Unrecognized property 'order' for class 'newSpotOrderObject.MARKET'.

### ISSUE THREAD

**Issue by stevelka** [hughestu/MATLAB-Binance-API#5]
Hi,

I try to make an order for example :

      bj = spot.newOrder('market')
     set(obj,'symb','btcusdt','side','buy','quant', 20,'isQuoteOrderQty')
     s = obj.send;

The first instruction to creat bj raises an error

Unrecognized property 'order' for class 'newSpotOrderObject.MARKET'.

Error in sortProps (line 15)
            obj.order = order;

Error in newSpotOrderObject.MARKET (line 30)
            obj@sortProps([2:4 1 5:8])

Error in spot.newOrder (line 85)
        obj = newSpotOrderObject.MARKET;

I am using Matlab R2021b

can you help please ?
thanks !

**Comment by hughestu** [comment]
It says that the property 'order' is unrecognized - have you modified sortProps (.../subfunctions/sortProps.m) in any way, specifically the order property in the properties block? Please confirm that lines 7-15 in sortProps are identical on your computer to the following:
```
    properties (GetAccess = private, Hidden = true)
        order
    end
    
    methods (Hidden)
        
        function obj = sortProps(order)
            obj.order = order;
        end
```

**Comment by stevelka** [comment]
You r right, my be I modofied it accidently,
now it works
Thanks bro

Your code is increadibly clean and easy to understand

**Comment by hughestu** [comment]
I figured that might be the case. No problem, I'm glad you like the code. If you get a chance, consider leaving a review on my [FEX submission](https://uk.mathworks.com/matlabcentral/fileexchange/95558-matlab-binance-api?s_tid=prof_contriblnk), I would appreciate it!
