### ISSUE TITLE
spot.newOrder('oco') :Server Error Code: -1013 Server Message: Duplicate order sent.

### ISSUE THREAD

**Issue by stevelka** [hughestu/MATLAB-Binance-API#6]
Hi,

I tried the function spot.newOrder for several options ('Limit', 'Market,'Stop Loss Limit'..) it works fine, but when
I tried it for OCO type orders  (I tryed it for sell),  it does not work.

what ever I try I got the message :
"
Error using sendRequest (line 81)
Client Error: Bad Request
Server Error Code: -1013
Server Message: Duplicate order sent.
"
even if there is no duplication (I mean I send the order for the first time!)

Can you help   solve this issu, please?

Thanks!

**Comment by stevelka** [comment]
The code I used is :
  obj = spot.newOrder('oco');
  set(obj,'symbol',handles.symbol,'side','sell',...
      'quantity',QtySell,...
      'price',LimitPrice,...
      'stopPrice',stopPrice,...
      'stopLimitPrice',stopLimitPrice,...
      'isTest',1)
  request = obj.send;

**Comment by hughestu** [comment]
It looks like you have found a bug that I need to fix. Some context: order ids have placeholder values of 0 in the OCO order object, and if the placeholder values for an order id is not specified by the user then it should not get sent to Binance. However, this is not happening right now, I found the following in my query string when I attempted to create an OCO order `&limitClientOrderId=0&stopClientOrderId=0`. 

Nicely spotted. I will push changes to fix this in the next day or so.

**Comment by stevelka** [comment]
Thanks bro, you r doing awsome job.

Have a nice day!

**Comment by stevelka** [comment]
hi, my be a little something to fixe ,
I tried the code  and got  the error:

Error using newSpotOrderObject.MARKET
File: G:\theRobot\subfunctions\+newSpotOrderObject\Order.m Line: 110 Column: 57
Invalid expression. When calling a function or indexing a variable, use parentheses. Otherwise, check for mismatched delimiters.


I did not try the oco margin order.

Thanks!
