### ISSUE TITLE
Linux

### ISSUE THREAD

**Issue by lilltroll77** [hughestu/MATLAB-Binance-API#7]
Hi again

FYI, Tried to run your API from Linux (instead of Windows), but since datetime reports more decimals
example
>> second(datetime)
ans =
   28.0966

some of your functions stops working.

It can easily be fixed with some round()

**Comment by hughestu** [comment]
Hi Mikael,

I hadn't tested on Linux prior to this but have now replicated the issue. Looks like it affects a few functions so I'll give this a better look later. Thanks.

**Comment by hughestu** [comment]
I saw you'd done this for `pub.klines` already, thanks. I figured this would need more consideration but it seems that the only other modification needed was in `datetime2posix()`.

**Comment by hughestu** [comment]
I will close this for now unless you notice something else. Thanks.
