### ISSUE TITLE
issues with pub.historicalTrades and pub.recenTrades

### ISSUE THREAD

**Issue by stevelka** [hughestu/MATLAB-Binance-API#8]
Hi,

I have found issues with the two functions
pub.historicalTrades and pub.recenTrades

The first does not work :
>> pub.historicalTrades('betabusd')
Not enough input arguments.

Error in sendRequest (line 39)
elseif OPT.xmapikey

Error in pub.historicalTrades (line 89)
response = sendRequest(OPT,endPoint,'GET');

the second function pub.recenTrades, not sure what it retrurns
I can try it with any coin (new one that I have never trades), I got thousands of records

Best regards!
have a nice day!

**Comment by hughestu** [comment]
`pub.recentTrades()` returns recently executed trades by **any user** on Binance. For trades on your own account, you need to look at spot, cmargin or imargin. I have updated the documentation to make it clearer that this function returns general market data.

Regarding `pub.historicalTrades()`, the endpoint appears to have been modified on the Binance side. Based on the response, this request now needs an API key in the header. I've updated the `pub.historicalTrades()` and it works fine now. 

You can download the latest version on GitHub and try:

`T = pub.historicalTrades('betabusd')`
`T = pub.historicalTrades('btcusdt')`

**Comment by stevelka** [comment]
Ok, thanks I understand

have a nice day
