### ISSUE TITLE
pub.exchaneInfo(),  isMarginTradingAllowed 

### ISSUE THREAD

**Issue by stevelka** [hughestu/MATLAB-Binance-API#9]
Hi,
there is an issue with pub.exchaneInfo() and the property  isMarginTradingAllowed .

this property can't be isCrossMarginTradingAllowed :
example 1 : pub.exchangeInfo('trbusdt').symbols
 isMarginTradingAllowed: 1
 But in Binance, only isolated trading is allowed for this symbol
 
 The property can't neither be isIsolatedMaginTradingAllowed  
 example 2 : pub.exchangeInfo('fxsbusd').symbols
  isMarginTradingAllowed: 0
But in Binance isolated trading is allowed for this symbol!

thanks bro for your awesome work!

have a nice day

**Comment by hughestu** [comment]
As far as I can see what you have pointed out is correct. However, `pub.exchangeInfo` returns a structure as provided by the Binance API, so I don't see how this could be an issue with the function. Both the parameter, isMarginTradingAllowed, and the values, 0 or 1, come directly from Binance. Look also at the permissions, Binance further indicates that margin trading is not permitted on FXS/BUSD even though the website suggests otherwise.

**Comment by hughestu** [comment]
I am closing this issue as I believe it is an error on the Binance side.

**Comment by stevelka** [comment]
Hi,

when isMarginTradingAllowed=1, is there a way to know if it s crossMargiAllowed, isolateMarginAllowed or both Allowed ?

Thanks for your work and your time sir
have a nice day!

**Comment by hughestu** [comment]
You could try something like this perhaps:

```
function tf = isCMarginTrading(symbol)

try
    info = cmargin.symbolInfo(symbol);
catch
    tf = false;
end

if exist('info','var')
    tf = info.isMarginTrade;
end
```

```
function tf = isIMarginTrading(symbol)

try
    info = imargin.symbolInfo(symbol);
catch
    tf = false;
end

if exist('info','var')
    tf = info.isMarginTrade;
end
```

**Comment by hughestu** [comment]
isMarginTradingAllowed is being deprecated from exchangeInfo(), so it's best not to write code based on that anyway. However, the above functions seem to give the right results. I'll let you test it.

**Comment by stevelka** [comment]
Great Idea,

thank you sir

have a nice day!

**Comment by hughestu** [comment]
No problem. This basically will ignore errors though, which isn't ideal, to say the least. Best to write something more like this:
```
try
    info = cmargin.symbolInfo(symbol);
    
catch ME
    
    if contains(ME.message,'Not a valid margin pair')
        tf = false;
    else
        rethrow(ME)
    end
end
```
